Lesson4 task2
Yetibjj/KotlinSprint pull request #17
Opened 2024-05-04 19:58 UTC by Yetibjj

2024-05-07 14:36 UTC, ievetrovdev requested changes

2024-05-07 14:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    val averageVolume = 100
Предлагаю переменные с которыми сравниваем входные данные вынести в константы, так как они точно не будут меняться после компиляции

2024-05-07 14:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    val cargo2Volume = 100
Еще предлагаю немного улучшить читабельность (на большом количестве кода это сыграет в плюс). Рекомендую блок с объявлением переменных группировать отделять пустой строкой от всего остального кода, а также внутренние условные выражения сверху и снизу обосабливать пустыми строка. Чтобы визуально они выделялись

2024-05-07 21:05 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    val averageVolume = 100
fix

2024-05-07 21:05 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    val cargo2Volume = 100
Да, ты ранее в задачах давал мне этот совет, а тут я что-то упустил( Поправил

2024-05-08 13:58 UTC, ievetrovdev approved these changes

2024-05-08 13:59 UTC, merged