Lesson4 task3
Yetibjj/KotlinSprint pull request #19
Opened 2024-05-05 18:55 UTC by Yetibjj

2024-05-06 17:59 UTC, ievetrovdev requested changes

2024-05-06 17:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val airHumidity = 20
Ты проинициализировал значения  с которыми должны сравниваются критерии (но не вижу переменную со временем года) 

Далее нужно проинициализировать сами критерии благоприятных условий, их кстати, стоит вынести в константы, так как они постоянные и не планируются изменяться после компиляции.

После сравнить их между собой

2024-05-06 17:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    var conditions = false
Рекомендуется Boolean переменные называть, "отвечая на вопрос“ да/нет. Ну и принято название начинать для них с is, в редких случаях has. Например, isConditions

2024-05-06 19:18 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val airHumidity = 20
fix

2024-05-06 19:18 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    var conditions = false
fix

2024-05-07 15:30 UTC, ievetrovdev requested changes

2024-05-07 15:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val season = "summer"
"Не зима" не значит лето) а по условию, текущее время года как раз зима, давай так и запишем в переменную, отрицание у тебя верно реализовано в коде условия

2024-05-07 15:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    var isConditions = false
Давай эту переменную инициализируем сразу выражением

2024-05-07 21:11 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val season = "summer"
fix

2024-05-07 21:40 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    var isConditions = false
Сделал, но не уверен, что это выглядит красиво

2024-05-08 14:02 UTC, ievetrovdev approved these changes

2024-05-08 14:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val isConditions = if (
Тут не нужна конструкция if-else, это выражение и так вернет true / false

2024-05-08 14:03 UTC, merged