Lesson4 task4
Yetibjj/KotlinSprint pull request #20
Opened 2024-05-05 19:27 UTC by Yetibjj

2024-05-06 18:32 UTC, ievetrovdev requested changes

2024-05-06 18:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    if (trainigDay % 2 == 0) {
Нужно немного изменить подход) Давай четность числа поместим в отдельный Boolean "флаг", например isEven и затем применим к каждой части тела напрямую или с отрицанием (инвертируя значение через символ `!`)

Флаг - можно сказать сленговое выражение "переключателя".  для отметки или указания определенного состояния. по аналогии с флагом, который поднимается или опускается для обозначения определенной ситуации, переменная может принимать одно из двух состояний.

2024-05-06 20:01 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    if (trainigDay % 2 == 0) {
Отправил исправленный вариант. Надеюсь, что правильно понял твой посыл

2024-05-07 15:45 UTC, ievetrovdev approved these changes

2024-05-07 15:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    if (trainigDay % 2 == 0) {
> Отправил исправленный вариант. Надеюсь, что правильно понял твой посыл

Почти)

fun main() {
    val trainigDay = 5
    val isEven = (trainigDay % 2 == 0)

    println("""
        "Упражнения для рук:    ${!isEven}"
        "Упражнения для ног:    $isEven"
        "Упражнения для спины:  $isEven"
        "Упражнения для пресса:  ${!isEven}"
    """.trimIndent())
}

2024-05-07 20:47 UTC, merged