Lesson4 task5
Yetibjj/KotlinSprint pull request #21
Opened 2024-05-06 16:29 UTC by Yetibjj

2024-05-07 14:27 UTC, ievetrovdev requested changes

2024-05-07 14:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val damage = readln().toBoolean()
Рекомендуется Boolean переменные называть, "отвечая на вопрос“ да/нет. Ну и принято название начинать для них с is, в редких случаях has. Например, hasDamage, isDamaged.

2024-05-07 14:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    if (!damage && (crewCount in 55..70) && supply >= 50 && weather) {
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не лучшая практика. добавь, пожалуйста, переменные) Эти переменные корректнее будет сделать константами, так как они не будут изменяться в коде после компиляции. Затем нужно будет в условии сравнить входящие данные с критериями.

В ветвлениях местами код продублирован. Чуть поменяем подход – чтобы сначала проинициализировать эти данные 1 раз. Затем создаем одно составное условие без if else, которое будет покрывать оба кейса. То есть примерно так будет выглядеть условно: (это и это и это) ИЛИ (это и это и это).

2024-05-07 21:49 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val damage = readln().toBoolean()
fix

2024-05-07 22:02 UTC, Yetibjj commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    if (!damage && (crewCount in 55..70) && supply >= 50 && weather) {
Спасибо, снова допустил эту ошибку с магическим числом. fix

2024-05-08 16:06 UTC, ievetrovdev approved these changes

2024-05-08 17:24 UTC, merged