Lesson5 task1
Yetibjj/KotlinSprint pull request #23
Opened 2024-05-06 17:15 UTC by Yetibjj

2024-05-07 19:19 UTC, ievetrovdev requested changes

2024-05-07 19:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    println("Введите ответ на следующее выражение: Два плюс пять умножить на 5")
Нам необходимо думать об обслуживании и расширяемости кода. Сумма должна считаться автоматически из объявленных заранее переменных. Поэтому так же не рекомендую использовать тут константу.

2024-05-07 22:11 UTC, Yetibjj commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    println("Введите ответ на следующее выражение: Два плюс пять умножить на 5")
fix

2024-05-08 16:07 UTC, ievetrovdev approved these changes

2024-05-08 17:25 UTC, merged