KS-1-5 create information of gagarin flight part3
Yetibjj/KotlinSprint pull request #5
Opened 2024-04-30 10:44 UTC by Yetibjj

2024-04-30 17:56 UTC, ievetrovdev requested changes

2024-04-30 17:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    val secondsPerHour = 3600
Вот это число должно вычисляться программно, человек, первый раз увидевший код, не поймет откуда оно взялось

2024-04-30 17:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    // Количество секунд в одном часе
Комментарии, не относящиеся к решению или не несущие никакой полезной нагрузки для будущего себя или других разработчиков в команде – лучше не оставлять в продакшн коде.

2024-04-30 17:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    var fullMinute = remainderOfSeconds / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-04-30 17:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    var fullSecond = remainderOfSeconds % 60
Эти переменные после инициализации никак не перезаписываются. Поэтому надо стараться по умолчанию всегда сразу писать val. Кроме того IDEA подсвечивает это сообщение варнингом.

2024-04-30 17:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("0$fullHour:$fullMinute:0$fullSecond")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-04-30 18:08 UTC, Yetibjj commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    val secondsPerHour = 3600
fix

2024-04-30 18:09 UTC, Yetibjj commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    // Количество секунд в одном часе
fix

2024-04-30 18:09 UTC, Yetibjj commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    var fullMinute = remainderOfSeconds / 60
fix

2024-04-30 18:09 UTC, Yetibjj commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    var fullSecond = remainderOfSeconds % 60
fix

2024-05-01 09:04 UTC, Yetibjj commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("0$fullHour:$fullMinute:0$fullSecond")
fix

2024-05-02 06:14 UTC, ievetrovdev approved these changes

2024-05-02 06:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println(formatTime(fullHour, fullMinute, fullSecond))
Все ок, но можно еще короче:
 println("%02d:%02d:%02d".format(fullHour, fullMinute, fullSecond)) 
и без дополнительной функции

2024-05-02 07:32 UTC, merged